version: '12-alpine'
services:
  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_db=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=222
